// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WardScreen.Models;

namespace WardScreen.Models
{
    public partial class IHMSContext
    {
        private IIHMSContextProcedures _procedures;

        public virtual IIHMSContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new IHMSContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IIHMSContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<spGetEminencePtResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<spScreenGetWardResult>().HasNoKey().ToView(null);
        }
    }

    public partial class IHMSContextProcedures : IIHMSContextProcedures
    {
        private readonly IHMSContext _context;

        public IHMSContextProcedures(IHMSContext context)
        {
            _context = context;
        }

        public virtual async Task<List<spGetEminencePtResult>> spGetEminencePtAsync(string vchCategory, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "vchCategory",
                    Size = 100,
                    Value = vchCategory ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetEminencePtResult>("EXEC @returnValue = [dbo].[spGetEminencePt] @vchCategory", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spScreenGetWardResult>> spScreenGetWardAsync(string vchWard, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "vchWard",
                    Size = 100,
                    Value = vchWard ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spScreenGetWardResult>("EXEC @returnValue = [dbo].[spScreenGetWard] @vchWard", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
