// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WardScreen.Models;

namespace WardScreen.Models
{
    public partial interface IIHMSContextProcedures
    {
        Task<List<spGetEminencePtResult>> spGetEminencePtAsync(string vchCategory, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spScreenGetWardResult>> spScreenGetWardAsync(string vchWard, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
