// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WardScreen.Models
{
    public partial class spScreenGetWardResult
    {
        public string opdno { get; set; }
        public string ipdno { get; set; }
        public string pname { get; set; }
        public string docid { get; set; }
        public string docname { get; set; }
        public string ward { get; set; }
        public string cward { get; set; }
        public string croom { get; set; }
        public string cbed { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime dtadmission { get; set; }
        public string pcode { get; set; }
        public string pcategory { get; set; }
    }
}
